// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package listutils.actions;

import listutils.ListUtils;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import javax.xml.transform.*;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;
import java.io.Reader;
import java.io.StringReader;
import java.io.StringWriter;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import org.apache.commons.lang.StringEscapeUtils;

/**
 * Generic list operation to process a given list of mendix objects using XSLT 2.0, e.g.
 * 
 * - Sort a list based on (multiple) expressions, not just plain attributes
 * - Filter a heterogenous list of objects based on their type
 * - Filter a list of objects by multiple attributes using complex expressions, not just based on an equality search on a single attribute
 */
public class FilterList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.util.List<IMendixObject> myList;
	private java.lang.String transformFn;

	public FilterList(IContext context, java.util.List<IMendixObject> myList, java.lang.String transformFn)
	{
		super(context);
		this.myList = myList;
		this.transformFn = transformFn;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = this.getContext();
		String myXML = ListUtils.SerializeList(context, this.myList);				
	
		// STEP 2: Apply the XSLT transformation using the Saxon parser	
		String myXSLT;
		myXSLT = "<xsl:stylesheet version=\"2.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">";
		myXSLT = myXSLT + "<xsl:output indent=\"no\" method=\"xml\"/>";
		myXSLT = myXSLT + " <xsl:template match=\"root\">";
		myXSLT = myXSLT + "  <root>" + this.transformFn + "</root>";
		myXSLT = myXSLT + " </xsl:template>";
		myXSLT = myXSLT + "</xsl:stylesheet>";

		StringWriter writer = new StringWriter();
		TransformerFactory tFactory = new net.sf.saxon.TransformerFactoryImpl();

		Transformer transformer = tFactory.newTransformer(new StreamSource(new StringReader(myXSLT)));
	        transformer.transform(new StreamSource(new StringReader(myXML)),new javax.xml.transform.stream.StreamResult(writer));

		// STEP 3: Return the list of objects in the output XML by performing a lookup for each object based on its Mendix identifier
		ArrayList<IMendixIdentifier> mxids = new ArrayList<IMendixIdentifier>();
       	        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
    		DocumentBuilder builder = factory.newDocumentBuilder();
		Document document = builder.parse(new InputSource(new StringReader(writer.toString())));
		NodeList nList = document.getDocumentElement().getChildNodes();
		for (int i = 0; i < nList.getLength(); i++) {
			Node node = nList.item(i);
			Element e = (Element)node;
			IMendixIdentifier mxid = Core.createMendixIdentifier(e.getAttribute("id"));
			mxids.add(mxid);	
		}
		return Core.retrieveIdList(context,mxids);
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "FilterList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
