// This file was generated by Mendix Modeler 7.8.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the PostalcodeHousenumber module

	/**
	* As described on https://data.pdok.nl/bag/api/v1/, the apikey is (2017 november) to be requested via mail 'dataplatform@kadaster.nl. It free of charge and only used to prevent abuse of this service. So request your own API-key.
	*/
	public static java.lang.String getAPIkey_NLBAG()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.APIkey_NLBAG");
	}

	public static java.lang.String getapikeydevelopment_password()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.apikeydevelopment_password");
	}

	public static java.lang.String getapikeydevelopment_username()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.apikeydevelopment_username");
	}

	public static java.lang.String getapikeyproduction_password()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.apikeyproduction_password");
	}

	public static java.lang.String getapikeyproduction_username()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.apikeyproduction_username");
	}

	/**
	* Canada Post Office
	*/
	public static java.lang.String getCA_PreferredSupplier()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.CA_PreferredSupplier");
	}

	/**
	* Endpoint of the API-service of Zippomoto.
	*/
	public static java.lang.String getendpoint_ALL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.endpoint_ALL");
	}

	/**
	* For addresses in Canada.
	*/
	public static java.lang.String getendpoint_CACPO()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.endpoint_CACPO");
	}

	/**
	* The webservice in NL is delivered by BAG: "Basis Administratie Gebouwen". This governmental company is part of the "Kadaster" and is the responsible party in NL for each building and address and all the data related to those buildings and addresses.
	* 
	* All information on their API: https://data.pdok.nl/bag/api/v1
	* 
	* More information on the kadaster: https://www.kadaster.nl/-/bag-linked-data-elke-dag-actueel-en-via-een-api-beschikbaar
	* And about their online viewer: https://bagviewer.kadaster.nl/lvbag/bag-viewer
	*/
	public static java.lang.String getendpoint_NLBAG()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.endpoint_NLBAG");
	}

	public static java.lang.String getendpoint_NLPDOK()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.endpoint_NLPDOK");
	}

	/**
	* For addresses in the USA.
	* 
	* I think: https://www.usps.com/business/web-tools-apis/
	*/
	public static java.lang.String getendpoint_USUSPS()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.endpoint_USUSPS");
	}

	public static java.lang.Long getMaxNrOfReturnedAddresses()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.MaxNrOfReturnedAddresses");
	}

	/**
	* Currently in NL there are two free suppliers:
	* - BAG, who is the source of all Dutch addressdata. Needs API-key and certificate and 4 API-calls.
	* - PDOK, who is a governmental, free and trustworthy supplier and has a simple interface.
	*/
	public static java.lang.String getNL_PreferredAPISupplier()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.NL_PreferredAPISupplier");
	}

	public static java.lang.String getUS_PreferredSupplier()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PostalcodeHousenumber.US_PreferredSupplier");
	}
}