// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package addresslookupapi.proxies;

public class PCAPredictResults
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pCAPredictResultsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AddressLookupAPI.PCAPredictResults";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_Id("_Id"),
		Text("Text"),
		Highlight("Highlight"),
		Cursor("Cursor"),
		Description("Description"),
		Next("Next"),
		MultiResult("AddressLookupAPI.MultiResult"),
		PCAPredictRetrieveAddress_PCAPredictResults("AddressLookupAPI.PCAPredictRetrieveAddress_PCAPredictResults");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PCAPredictResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AddressLookupAPI.PCAPredictResults"));
	}

	protected PCAPredictResults(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pCAPredictResultsMendixObject)
	{
		if (pCAPredictResultsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AddressLookupAPI.PCAPredictResults", pCAPredictResultsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AddressLookupAPI.PCAPredictResults");

		this.pCAPredictResultsMendixObject = pCAPredictResultsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PCAPredictResults.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static addresslookupapi.proxies.PCAPredictResults initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return addresslookupapi.proxies.PCAPredictResults.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static addresslookupapi.proxies.PCAPredictResults initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new addresslookupapi.proxies.PCAPredictResults(context, mendixObject);
	}

	public static addresslookupapi.proxies.PCAPredictResults load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return addresslookupapi.proxies.PCAPredictResults.initialize(context, mendixObject);
	}

	public static java.util.List<addresslookupapi.proxies.PCAPredictResults> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<addresslookupapi.proxies.PCAPredictResults> result = new java.util.ArrayList<addresslookupapi.proxies.PCAPredictResults>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AddressLookupAPI.PCAPredictResults" + xpathConstraint))
			result.add(addresslookupapi.proxies.PCAPredictResults.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _Id
	 */
	public final java.lang.String get_Id()
	{
		return get_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of _Id
	 */
	public final java.lang.String get_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Id.toString());
	}

	/**
	 * Set value of _Id
	 * @param _id
	 */
	public final void set_Id(java.lang.String _id)
	{
		set_Id(getContext(), _id);
	}

	/**
	 * Set value of _Id
	 * @param context
	 * @param _id
	 */
	public final void set_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._Id.toString(), _id);
	}

	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of Highlight
	 */
	public final java.lang.String getHighlight()
	{
		return getHighlight(getContext());
	}

	/**
	 * @param context
	 * @return value of Highlight
	 */
	public final java.lang.String getHighlight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Highlight.toString());
	}

	/**
	 * Set value of Highlight
	 * @param highlight
	 */
	public final void setHighlight(java.lang.String highlight)
	{
		setHighlight(getContext(), highlight);
	}

	/**
	 * Set value of Highlight
	 * @param context
	 * @param highlight
	 */
	public final void setHighlight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String highlight)
	{
		getMendixObject().setValue(context, MemberNames.Highlight.toString(), highlight);
	}

	/**
	 * @return value of Cursor
	 */
	public final java.lang.Integer getCursor()
	{
		return getCursor(getContext());
	}

	/**
	 * @param context
	 * @return value of Cursor
	 */
	public final java.lang.Integer getCursor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Cursor.toString());
	}

	/**
	 * Set value of Cursor
	 * @param cursor
	 */
	public final void setCursor(java.lang.Integer cursor)
	{
		setCursor(getContext(), cursor);
	}

	/**
	 * Set value of Cursor
	 * @param context
	 * @param cursor
	 */
	public final void setCursor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cursor)
	{
		getMendixObject().setValue(context, MemberNames.Cursor.toString(), cursor);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Next
	 */
	public final java.lang.String getNext()
	{
		return getNext(getContext());
	}

	/**
	 * @param context
	 * @return value of Next
	 */
	public final java.lang.String getNext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Next.toString());
	}

	/**
	 * Set value of Next
	 * @param next
	 */
	public final void setNext(java.lang.String next)
	{
		setNext(getContext(), next);
	}

	/**
	 * Set value of Next
	 * @param context
	 * @param next
	 */
	public final void setNext(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String next)
	{
		getMendixObject().setValue(context, MemberNames.Next.toString(), next);
	}

	/**
	 * @return value of MultiResult
	 */
	public final java.util.List<addresslookupapi.proxies.PCAPredictRequest> getMultiResult() throws com.mendix.core.CoreException
	{
		return getMultiResult(getContext());
	}

	/**
	 * @param context
	 * @return value of MultiResult
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<addresslookupapi.proxies.PCAPredictRequest> getMultiResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<addresslookupapi.proxies.PCAPredictRequest> result = new java.util.ArrayList<addresslookupapi.proxies.PCAPredictRequest>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MultiResult.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(addresslookupapi.proxies.PCAPredictRequest.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of MultiResult
	 * @param multiresult
	 */
	public final void setMultiResult(java.util.List<addresslookupapi.proxies.PCAPredictRequest> multiresult)
	{
		setMultiResult(getContext(), multiresult);
	}

	/**
	 * Set value of MultiResult
	 * @param context
	 * @param multiresult
	 */
	public final void setMultiResult(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<addresslookupapi.proxies.PCAPredictRequest> multiresult)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (addresslookupapi.proxies.PCAPredictRequest proxyObject : multiresult)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.MultiResult.toString(), identifiers);
	}

	/**
	 * @return value of PCAPredictRetrieveAddress_PCAPredictResults
	 */
	public final addresslookupapi.proxies.PCAPredictRetrieveAddress getPCAPredictRetrieveAddress_PCAPredictResults() throws com.mendix.core.CoreException
	{
		return getPCAPredictRetrieveAddress_PCAPredictResults(getContext());
	}

	/**
	 * @param context
	 * @return value of PCAPredictRetrieveAddress_PCAPredictResults
	 */
	public final addresslookupapi.proxies.PCAPredictRetrieveAddress getPCAPredictRetrieveAddress_PCAPredictResults(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		addresslookupapi.proxies.PCAPredictRetrieveAddress result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PCAPredictRetrieveAddress_PCAPredictResults.toString());
		if (identifier != null)
			result = addresslookupapi.proxies.PCAPredictRetrieveAddress.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PCAPredictRetrieveAddress_PCAPredictResults
	 * @param pcapredictretrieveaddress_pcapredictresults
	 */
	public final void setPCAPredictRetrieveAddress_PCAPredictResults(addresslookupapi.proxies.PCAPredictRetrieveAddress pcapredictretrieveaddress_pcapredictresults)
	{
		setPCAPredictRetrieveAddress_PCAPredictResults(getContext(), pcapredictretrieveaddress_pcapredictresults);
	}

	/**
	 * Set value of PCAPredictRetrieveAddress_PCAPredictResults
	 * @param context
	 * @param pcapredictretrieveaddress_pcapredictresults
	 */
	public final void setPCAPredictRetrieveAddress_PCAPredictResults(com.mendix.systemwideinterfaces.core.IContext context, addresslookupapi.proxies.PCAPredictRetrieveAddress pcapredictretrieveaddress_pcapredictresults)
	{
		if (pcapredictretrieveaddress_pcapredictresults == null)
			getMendixObject().setValue(context, MemberNames.PCAPredictRetrieveAddress_PCAPredictResults.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PCAPredictRetrieveAddress_PCAPredictResults.toString(), pcapredictretrieveaddress_pcapredictresults.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pCAPredictResultsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final addresslookupapi.proxies.PCAPredictResults that = (addresslookupapi.proxies.PCAPredictResults) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AddressLookupAPI.PCAPredictResults";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
