// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package addresslookupapi.proxies;

public class PCAPredictRequest
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pCAPredictRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AddressLookupAPI.PCAPredictRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		SearchTerm("SearchTerm"),
		LastId("LastId"),
		SearchFor("SearchFor"),
		Country("Country"),
		LanguagePreference("LanguagePreference"),
		MaxSuggestions("MaxSuggestions"),
		MaxResults("MaxResults"),
		HouseNo("HouseNo"),
		Postcode("Postcode"),
		ShowAddressList("ShowAddressList"),
		ShowAddress("ShowAddress"),
		MultiResult("AddressLookupAPI.MultiResult"),
		PCAPredictRequest_PCAPredictResults("AddressLookupAPI.PCAPredictRequest_PCAPredictResults"),
		Address_PCAPredictRequest("AddressLookupAPI.Address_PCAPredictRequest");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PCAPredictRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AddressLookupAPI.PCAPredictRequest"));
	}

	protected PCAPredictRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pCAPredictRequestMendixObject)
	{
		if (pCAPredictRequestMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AddressLookupAPI.PCAPredictRequest", pCAPredictRequestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AddressLookupAPI.PCAPredictRequest");

		this.pCAPredictRequestMendixObject = pCAPredictRequestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PCAPredictRequest.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static addresslookupapi.proxies.PCAPredictRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return addresslookupapi.proxies.PCAPredictRequest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static addresslookupapi.proxies.PCAPredictRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new addresslookupapi.proxies.PCAPredictRequest(context, mendixObject);
	}

	public static addresslookupapi.proxies.PCAPredictRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return addresslookupapi.proxies.PCAPredictRequest.initialize(context, mendixObject);
	}

	public static java.util.List<addresslookupapi.proxies.PCAPredictRequest> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<addresslookupapi.proxies.PCAPredictRequest> result = new java.util.ArrayList<addresslookupapi.proxies.PCAPredictRequest>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AddressLookupAPI.PCAPredictRequest" + xpathConstraint))
			result.add(addresslookupapi.proxies.PCAPredictRequest.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of SearchTerm
	 */
	public final java.lang.String getSearchTerm()
	{
		return getSearchTerm(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchTerm
	 */
	public final java.lang.String getSearchTerm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SearchTerm.toString());
	}

	/**
	 * Set value of SearchTerm
	 * @param searchterm
	 */
	public final void setSearchTerm(java.lang.String searchterm)
	{
		setSearchTerm(getContext(), searchterm);
	}

	/**
	 * Set value of SearchTerm
	 * @param context
	 * @param searchterm
	 */
	public final void setSearchTerm(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String searchterm)
	{
		getMendixObject().setValue(context, MemberNames.SearchTerm.toString(), searchterm);
	}

	/**
	 * @return value of LastId
	 */
	public final java.lang.String getLastId()
	{
		return getLastId(getContext());
	}

	/**
	 * @param context
	 * @return value of LastId
	 */
	public final java.lang.String getLastId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastId.toString());
	}

	/**
	 * Set value of LastId
	 * @param lastid
	 */
	public final void setLastId(java.lang.String lastid)
	{
		setLastId(getContext(), lastid);
	}

	/**
	 * Set value of LastId
	 * @param context
	 * @param lastid
	 */
	public final void setLastId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastid)
	{
		getMendixObject().setValue(context, MemberNames.LastId.toString(), lastid);
	}

	/**
	 * Set value of SearchFor
	 * @param searchfor
	 */
	public final addresslookupapi.proxies.SearchFor getSearchFor()
	{
		return getSearchFor(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchFor
	 */
	public final addresslookupapi.proxies.SearchFor getSearchFor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SearchFor.toString());
		if (obj == null)
			return null;

		return addresslookupapi.proxies.SearchFor.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SearchFor
	 * @param searchfor
	 */
	public final void setSearchFor(addresslookupapi.proxies.SearchFor searchfor)
	{
		setSearchFor(getContext(), searchfor);
	}

	/**
	 * Set value of SearchFor
	 * @param context
	 * @param searchfor
	 */
	public final void setSearchFor(com.mendix.systemwideinterfaces.core.IContext context, addresslookupapi.proxies.SearchFor searchfor)
	{
		if (searchfor != null)
			getMendixObject().setValue(context, MemberNames.SearchFor.toString(), searchfor.toString());
		else
			getMendixObject().setValue(context, MemberNames.SearchFor.toString(), null);
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final addresslookupapi.proxies.Countries getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final addresslookupapi.proxies.Countries getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Country.toString());
		if (obj == null)
			return null;

		return addresslookupapi.proxies.Countries.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(addresslookupapi.proxies.Countries country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, addresslookupapi.proxies.Countries country)
	{
		if (country != null)
			getMendixObject().setValue(context, MemberNames.Country.toString(), country.toString());
		else
			getMendixObject().setValue(context, MemberNames.Country.toString(), null);
	}

	/**
	 * @return value of LanguagePreference
	 */
	public final java.lang.String getLanguagePreference()
	{
		return getLanguagePreference(getContext());
	}

	/**
	 * @param context
	 * @return value of LanguagePreference
	 */
	public final java.lang.String getLanguagePreference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LanguagePreference.toString());
	}

	/**
	 * Set value of LanguagePreference
	 * @param languagepreference
	 */
	public final void setLanguagePreference(java.lang.String languagepreference)
	{
		setLanguagePreference(getContext(), languagepreference);
	}

	/**
	 * Set value of LanguagePreference
	 * @param context
	 * @param languagepreference
	 */
	public final void setLanguagePreference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String languagepreference)
	{
		getMendixObject().setValue(context, MemberNames.LanguagePreference.toString(), languagepreference);
	}

	/**
	 * @return value of MaxSuggestions
	 */
	public final java.lang.Integer getMaxSuggestions()
	{
		return getMaxSuggestions(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxSuggestions
	 */
	public final java.lang.Integer getMaxSuggestions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxSuggestions.toString());
	}

	/**
	 * Set value of MaxSuggestions
	 * @param maxsuggestions
	 */
	public final void setMaxSuggestions(java.lang.Integer maxsuggestions)
	{
		setMaxSuggestions(getContext(), maxsuggestions);
	}

	/**
	 * Set value of MaxSuggestions
	 * @param context
	 * @param maxsuggestions
	 */
	public final void setMaxSuggestions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxsuggestions)
	{
		getMendixObject().setValue(context, MemberNames.MaxSuggestions.toString(), maxsuggestions);
	}

	/**
	 * @return value of MaxResults
	 */
	public final java.lang.Integer getMaxResults()
	{
		return getMaxResults(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxResults
	 */
	public final java.lang.Integer getMaxResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxResults.toString());
	}

	/**
	 * Set value of MaxResults
	 * @param maxresults
	 */
	public final void setMaxResults(java.lang.Integer maxresults)
	{
		setMaxResults(getContext(), maxresults);
	}

	/**
	 * Set value of MaxResults
	 * @param context
	 * @param maxresults
	 */
	public final void setMaxResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxresults)
	{
		getMendixObject().setValue(context, MemberNames.MaxResults.toString(), maxresults);
	}

	/**
	 * @return value of HouseNo
	 */
	public final java.lang.String getHouseNo()
	{
		return getHouseNo(getContext());
	}

	/**
	 * @param context
	 * @return value of HouseNo
	 */
	public final java.lang.String getHouseNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HouseNo.toString());
	}

	/**
	 * Set value of HouseNo
	 * @param houseno
	 */
	public final void setHouseNo(java.lang.String houseno)
	{
		setHouseNo(getContext(), houseno);
	}

	/**
	 * Set value of HouseNo
	 * @param context
	 * @param houseno
	 */
	public final void setHouseNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String houseno)
	{
		getMendixObject().setValue(context, MemberNames.HouseNo.toString(), houseno);
	}

	/**
	 * @return value of Postcode
	 */
	public final java.lang.String getPostcode()
	{
		return getPostcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Postcode
	 */
	public final java.lang.String getPostcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Postcode.toString());
	}

	/**
	 * Set value of Postcode
	 * @param postcode
	 */
	public final void setPostcode(java.lang.String postcode)
	{
		setPostcode(getContext(), postcode);
	}

	/**
	 * Set value of Postcode
	 * @param context
	 * @param postcode
	 */
	public final void setPostcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postcode)
	{
		getMendixObject().setValue(context, MemberNames.Postcode.toString(), postcode);
	}

	/**
	 * @return value of ShowAddressList
	 */
	public final java.lang.Boolean getShowAddressList()
	{
		return getShowAddressList(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddressList
	 */
	public final java.lang.Boolean getShowAddressList(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddressList.toString());
	}

	/**
	 * Set value of ShowAddressList
	 * @param showaddresslist
	 */
	public final void setShowAddressList(java.lang.Boolean showaddresslist)
	{
		setShowAddressList(getContext(), showaddresslist);
	}

	/**
	 * Set value of ShowAddressList
	 * @param context
	 * @param showaddresslist
	 */
	public final void setShowAddressList(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddresslist)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddressList.toString(), showaddresslist);
	}

	/**
	 * @return value of ShowAddress
	 */
	public final java.lang.Boolean getShowAddress()
	{
		return getShowAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddress
	 */
	public final java.lang.Boolean getShowAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddress.toString());
	}

	/**
	 * Set value of ShowAddress
	 * @param showaddress
	 */
	public final void setShowAddress(java.lang.Boolean showaddress)
	{
		setShowAddress(getContext(), showaddress);
	}

	/**
	 * Set value of ShowAddress
	 * @param context
	 * @param showaddress
	 */
	public final void setShowAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddress)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddress.toString(), showaddress);
	}

	/**
	 * @return value of MultiResult
	 */
	public final java.util.List<addresslookupapi.proxies.PCAPredictResults> getMultiResult() throws com.mendix.core.CoreException
	{
		return getMultiResult(getContext());
	}

	/**
	 * @param context
	 * @return value of MultiResult
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<addresslookupapi.proxies.PCAPredictResults> getMultiResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<addresslookupapi.proxies.PCAPredictResults> result = new java.util.ArrayList<addresslookupapi.proxies.PCAPredictResults>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MultiResult.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(addresslookupapi.proxies.PCAPredictResults.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of MultiResult
	 * @param multiresult
	 */
	public final void setMultiResult(java.util.List<addresslookupapi.proxies.PCAPredictResults> multiresult)
	{
		setMultiResult(getContext(), multiresult);
	}

	/**
	 * Set value of MultiResult
	 * @param context
	 * @param multiresult
	 */
	public final void setMultiResult(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<addresslookupapi.proxies.PCAPredictResults> multiresult)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (addresslookupapi.proxies.PCAPredictResults proxyObject : multiresult)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.MultiResult.toString(), identifiers);
	}

	/**
	 * @return value of PCAPredictRequest_PCAPredictResults
	 */
	public final addresslookupapi.proxies.PCAPredictResults getPCAPredictRequest_PCAPredictResults() throws com.mendix.core.CoreException
	{
		return getPCAPredictRequest_PCAPredictResults(getContext());
	}

	/**
	 * @param context
	 * @return value of PCAPredictRequest_PCAPredictResults
	 */
	public final addresslookupapi.proxies.PCAPredictResults getPCAPredictRequest_PCAPredictResults(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		addresslookupapi.proxies.PCAPredictResults result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PCAPredictRequest_PCAPredictResults.toString());
		if (identifier != null)
			result = addresslookupapi.proxies.PCAPredictResults.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PCAPredictRequest_PCAPredictResults
	 * @param pcapredictrequest_pcapredictresults
	 */
	public final void setPCAPredictRequest_PCAPredictResults(addresslookupapi.proxies.PCAPredictResults pcapredictrequest_pcapredictresults)
	{
		setPCAPredictRequest_PCAPredictResults(getContext(), pcapredictrequest_pcapredictresults);
	}

	/**
	 * Set value of PCAPredictRequest_PCAPredictResults
	 * @param context
	 * @param pcapredictrequest_pcapredictresults
	 */
	public final void setPCAPredictRequest_PCAPredictResults(com.mendix.systemwideinterfaces.core.IContext context, addresslookupapi.proxies.PCAPredictResults pcapredictrequest_pcapredictresults)
	{
		if (pcapredictrequest_pcapredictresults == null)
			getMendixObject().setValue(context, MemberNames.PCAPredictRequest_PCAPredictResults.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PCAPredictRequest_PCAPredictResults.toString(), pcapredictrequest_pcapredictresults.getMendixObject().getId());
	}

	/**
	 * @return value of Address_PCAPredictRequest
	 */
	public final addresslookupapi.proxies.Address getAddress_PCAPredictRequest() throws com.mendix.core.CoreException
	{
		return getAddress_PCAPredictRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Address_PCAPredictRequest
	 */
	public final addresslookupapi.proxies.Address getAddress_PCAPredictRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		addresslookupapi.proxies.Address result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Address_PCAPredictRequest.toString());
		if (identifier != null)
			result = addresslookupapi.proxies.Address.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Address_PCAPredictRequest
	 * @param address_pcapredictrequest
	 */
	public final void setAddress_PCAPredictRequest(addresslookupapi.proxies.Address address_pcapredictrequest)
	{
		setAddress_PCAPredictRequest(getContext(), address_pcapredictrequest);
	}

	/**
	 * Set value of Address_PCAPredictRequest
	 * @param context
	 * @param address_pcapredictrequest
	 */
	public final void setAddress_PCAPredictRequest(com.mendix.systemwideinterfaces.core.IContext context, addresslookupapi.proxies.Address address_pcapredictrequest)
	{
		if (address_pcapredictrequest == null)
			getMendixObject().setValue(context, MemberNames.Address_PCAPredictRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Address_PCAPredictRequest.toString(), address_pcapredictrequest.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pCAPredictRequestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final addresslookupapi.proxies.PCAPredictRequest that = (addresslookupapi.proxies.PCAPredictRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AddressLookupAPI.PCAPredictRequest";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
