// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package flatfileinterface.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import flatfileinterface.proxies.FileEncoding;

public class JA_StringToFileEncoding extends CustomJavaAction<java.lang.String>
{
	private java.lang.String param;

	public JA_StringToFileEncoding(IContext context, java.lang.String param)
	{
		super(context);
		this.param = param;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (param == null || param.isEmpty() || FileEncoding.valueOf(param) == null)
			return null;
		return FileEncoding.valueOf(param).toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "JA_StringToFileEncoding";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
