// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package flatfileinterface.proxies;

public enum FileEncoding
{
	UTF8(new java.lang.String[][] { new java.lang.String[] { "en_US", "UTF8" }, new java.lang.String[] { "nl_NL", "UTF8" } }),
	Cp1252(new java.lang.String[][] { new java.lang.String[] { "en_US", "Cp1252" }, new java.lang.String[] { "nl_NL", "Cp1252" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private FileEncoding(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
