// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package flatfileinterface.proxies;

public class ImportExportDocument extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FlatFileInterface.ImportExportDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ImportExportDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "FlatFileInterface.ImportExportDocument"));
	}

	protected ImportExportDocument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject importExportDocumentMendixObject)
	{
		super(context, importExportDocumentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("FlatFileInterface.ImportExportDocument", importExportDocumentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a FlatFileInterface.ImportExportDocument");
	}

	/**
	 * @deprecated Use 'ImportExportDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static flatfileinterface.proxies.ImportExportDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return flatfileinterface.proxies.ImportExportDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static flatfileinterface.proxies.ImportExportDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new flatfileinterface.proxies.ImportExportDocument(context, mendixObject);
	}

	public static flatfileinterface.proxies.ImportExportDocument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return flatfileinterface.proxies.ImportExportDocument.initialize(context, mendixObject);
	}

	public static java.util.List<flatfileinterface.proxies.ImportExportDocument> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<flatfileinterface.proxies.ImportExportDocument> result = new java.util.ArrayList<flatfileinterface.proxies.ImportExportDocument>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//FlatFileInterface.ImportExportDocument" + xpathConstraint))
			result.add(flatfileinterface.proxies.ImportExportDocument.initialize(context, obj));
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final flatfileinterface.proxies.ImportExportDocument that = (flatfileinterface.proxies.ImportExportDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "FlatFileInterface.ImportExportDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
