// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package flatfileinterface.proxies;

public enum IntervalType
{
	Minute(new java.lang.String[][] { new java.lang.String[] { "en_US", "Minute(s)" }, new java.lang.String[] { "nl_NL", "Minuten" } }),
	Hour(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hour(s)" }, new java.lang.String[] { "nl_NL", "Uren" } }),
	Day(new java.lang.String[][] { new java.lang.String[] { "en_US", "Day(s)" }, new java.lang.String[] { "nl_NL", "Dagen" } }),
	Week(new java.lang.String[][] { new java.lang.String[] { "en_US", "Week(s)" }, new java.lang.String[] { "nl_NL", "Weken" } }),
	Month(new java.lang.String[][] { new java.lang.String[] { "en_US", "Month(s)" }, new java.lang.String[] { "nl_NL", "Maand(en)" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private IntervalType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
