// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package flatfileinterface.proxies;

public class Log
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject logMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FlatFileInterface.Log";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LogDate("LogDate"),
		Log_InterfaceDefinition("FlatFileInterface.Log_InterfaceDefinition");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Log(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "FlatFileInterface.Log"));
	}

	protected Log(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject logMendixObject)
	{
		if (logMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("FlatFileInterface.Log", logMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a FlatFileInterface.Log");

		this.logMendixObject = logMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Log.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static flatfileinterface.proxies.Log initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return flatfileinterface.proxies.Log.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static flatfileinterface.proxies.Log initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new flatfileinterface.proxies.Log(context, mendixObject);
	}

	public static flatfileinterface.proxies.Log load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return flatfileinterface.proxies.Log.initialize(context, mendixObject);
	}

	public static java.util.List<flatfileinterface.proxies.Log> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<flatfileinterface.proxies.Log> result = new java.util.ArrayList<flatfileinterface.proxies.Log>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//FlatFileInterface.Log" + xpathConstraint))
			result.add(flatfileinterface.proxies.Log.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of LogDate
	 */
	public final java.util.Date getLogDate()
	{
		return getLogDate(getContext());
	}

	/**
	 * @param context
	 * @return value of LogDate
	 */
	public final java.util.Date getLogDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LogDate.toString());
	}

	/**
	 * Set value of LogDate
	 * @param logdate
	 */
	public final void setLogDate(java.util.Date logdate)
	{
		setLogDate(getContext(), logdate);
	}

	/**
	 * Set value of LogDate
	 * @param context
	 * @param logdate
	 */
	public final void setLogDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date logdate)
	{
		getMendixObject().setValue(context, MemberNames.LogDate.toString(), logdate);
	}

	/**
	 * @return value of Log_InterfaceDefinition
	 */
	public final flatfileinterface.proxies.InterfaceDefinition getLog_InterfaceDefinition() throws com.mendix.core.CoreException
	{
		return getLog_InterfaceDefinition(getContext());
	}

	/**
	 * @param context
	 * @return value of Log_InterfaceDefinition
	 */
	public final flatfileinterface.proxies.InterfaceDefinition getLog_InterfaceDefinition(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		flatfileinterface.proxies.InterfaceDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Log_InterfaceDefinition.toString());
		if (identifier != null)
			result = flatfileinterface.proxies.InterfaceDefinition.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Log_InterfaceDefinition
	 * @param log_interfacedefinition
	 */
	public final void setLog_InterfaceDefinition(flatfileinterface.proxies.InterfaceDefinition log_interfacedefinition)
	{
		setLog_InterfaceDefinition(getContext(), log_interfacedefinition);
	}

	/**
	 * Set value of Log_InterfaceDefinition
	 * @param context
	 * @param log_interfacedefinition
	 */
	public final void setLog_InterfaceDefinition(com.mendix.systemwideinterfaces.core.IContext context, flatfileinterface.proxies.InterfaceDefinition log_interfacedefinition)
	{
		if (log_interfacedefinition == null)
			getMendixObject().setValue(context, MemberNames.Log_InterfaceDefinition.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Log_InterfaceDefinition.toString(), log_interfacedefinition.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return logMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final flatfileinterface.proxies.Log that = (flatfileinterface.proxies.Log) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "FlatFileInterface.Log";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
