// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package flatfileinterface.proxies;

public class ProcesFileQueue extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FlatFileInterface.ProcesFileQueue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		QueueNumber("QueueNumber"),
		Processed("Processed"),
		Error("Error"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProcesFileQueue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "FlatFileInterface.ProcesFileQueue"));
	}

	protected ProcesFileQueue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject procesFileQueueMendixObject)
	{
		super(context, procesFileQueueMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("FlatFileInterface.ProcesFileQueue", procesFileQueueMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a FlatFileInterface.ProcesFileQueue");
	}

	/**
	 * @deprecated Use 'ProcesFileQueue.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static flatfileinterface.proxies.ProcesFileQueue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return flatfileinterface.proxies.ProcesFileQueue.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static flatfileinterface.proxies.ProcesFileQueue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new flatfileinterface.proxies.ProcesFileQueue(context, mendixObject);
	}

	public static flatfileinterface.proxies.ProcesFileQueue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return flatfileinterface.proxies.ProcesFileQueue.initialize(context, mendixObject);
	}

	public static java.util.List<flatfileinterface.proxies.ProcesFileQueue> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<flatfileinterface.proxies.ProcesFileQueue> result = new java.util.ArrayList<flatfileinterface.proxies.ProcesFileQueue>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//FlatFileInterface.ProcesFileQueue" + xpathConstraint))
			result.add(flatfileinterface.proxies.ProcesFileQueue.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of QueueNumber
	 */
	public final java.lang.Integer getQueueNumber()
	{
		return getQueueNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of QueueNumber
	 */
	public final java.lang.Integer getQueueNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.QueueNumber.toString());
	}

	/**
	 * Set value of QueueNumber
	 * @param queuenumber
	 */
	public final void setQueueNumber(java.lang.Integer queuenumber)
	{
		setQueueNumber(getContext(), queuenumber);
	}

	/**
	 * Set value of QueueNumber
	 * @param context
	 * @param queuenumber
	 */
	public final void setQueueNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer queuenumber)
	{
		getMendixObject().setValue(context, MemberNames.QueueNumber.toString(), queuenumber);
	}

	/**
	 * @return value of Processed
	 */
	public final java.lang.Boolean getProcessed()
	{
		return getProcessed(getContext());
	}

	/**
	 * @param context
	 * @return value of Processed
	 */
	public final java.lang.Boolean getProcessed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Processed.toString());
	}

	/**
	 * Set value of Processed
	 * @param processed
	 */
	public final void setProcessed(java.lang.Boolean processed)
	{
		setProcessed(getContext(), processed);
	}

	/**
	 * Set value of Processed
	 * @param context
	 * @param processed
	 */
	public final void setProcessed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processed)
	{
		getMendixObject().setValue(context, MemberNames.Processed.toString(), processed);
	}

	/**
	 * @return value of Error
	 */
	public final java.lang.Boolean getError()
	{
		return getError(getContext());
	}

	/**
	 * @param context
	 * @return value of Error
	 */
	public final java.lang.Boolean getError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Error.toString());
	}

	/**
	 * Set value of Error
	 * @param error
	 */
	public final void setError(java.lang.Boolean error)
	{
		setError(getContext(), error);
	}

	/**
	 * Set value of Error
	 * @param context
	 * @param error
	 */
	public final void setError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean error)
	{
		getMendixObject().setValue(context, MemberNames.Error.toString(), error);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final flatfileinterface.proxies.ProcesFileQueue that = (flatfileinterface.proxies.ProcesFileQueue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "FlatFileInterface.ProcesFileQueue";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
