// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package listutils.proxies;

public class Person
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject personMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ListUtils.Person";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		firstname("firstname"),
		lastname("lastname"),
		salary("salary"),
		bla("bla");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Person(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ListUtils.Person"));
	}

	protected Person(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject personMendixObject)
	{
		if (personMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ListUtils.Person", personMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ListUtils.Person");

		this.personMendixObject = personMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Person.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static listutils.proxies.Person initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return listutils.proxies.Person.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static listutils.proxies.Person initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new listutils.proxies.Person(context, mendixObject);
	}

	public static listutils.proxies.Person load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return listutils.proxies.Person.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of firstname
	 */
	public final java.lang.String getfirstname()
	{
		return getfirstname(getContext());
	}

	/**
	 * @param context
	 * @return value of firstname
	 */
	public final java.lang.String getfirstname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.firstname.toString());
	}

	/**
	 * Set value of firstname
	 * @param firstname
	 */
	public final void setfirstname(java.lang.String firstname)
	{
		setfirstname(getContext(), firstname);
	}

	/**
	 * Set value of firstname
	 * @param context
	 * @param firstname
	 */
	public final void setfirstname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.firstname.toString(), firstname);
	}

	/**
	 * @return value of lastname
	 */
	public final java.lang.String getlastname()
	{
		return getlastname(getContext());
	}

	/**
	 * @param context
	 * @return value of lastname
	 */
	public final java.lang.String getlastname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.lastname.toString());
	}

	/**
	 * Set value of lastname
	 * @param lastname
	 */
	public final void setlastname(java.lang.String lastname)
	{
		setlastname(getContext(), lastname);
	}

	/**
	 * Set value of lastname
	 * @param context
	 * @param lastname
	 */
	public final void setlastname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.lastname.toString(), lastname);
	}

	/**
	 * @return value of salary
	 */
	public final java.lang.Integer getsalary()
	{
		return getsalary(getContext());
	}

	/**
	 * @param context
	 * @return value of salary
	 */
	public final java.lang.Integer getsalary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.salary.toString());
	}

	/**
	 * Set value of salary
	 * @param salary
	 */
	public final void setsalary(java.lang.Integer salary)
	{
		setsalary(getContext(), salary);
	}

	/**
	 * Set value of salary
	 * @param context
	 * @param salary
	 */
	public final void setsalary(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer salary)
	{
		getMendixObject().setValue(context, MemberNames.salary.toString(), salary);
	}

	/**
	 * @return value of bla
	 */
	public final java.lang.String getbla()
	{
		return getbla(getContext());
	}

	/**
	 * @param context
	 * @return value of bla
	 */
	public final java.lang.String getbla(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.bla.toString());
	}

	/**
	 * Set value of bla
	 * @param bla
	 */
	public final void setbla(java.lang.String bla)
	{
		setbla(getContext(), bla);
	}

	/**
	 * Set value of bla
	 * @param context
	 * @param bla
	 */
	public final void setbla(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bla)
	{
		getMendixObject().setValue(context, MemberNames.bla.toString(), bla);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return personMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final listutils.proxies.Person that = (listutils.proxies.Person) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ListUtils.Person";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
