// This file was generated by Mendix Modeler 7.8.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the PostalcodeHousenumber module
	public static postalcodehousenumber.proxies.Address aCT_Address_CreateEmptyObject(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "PostalcodeHousenumber.ACT_Address_CreateEmptyObject", params);
			return result == null ? null : postalcodehousenumber.proxies.Address.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static postalcodehousenumber.proxies.Returnvalues aCT_Address_GetSingleAddress(IContext context, postalcodehousenumber.proxies.inputparameters _inputparameters)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("inputparameters", _inputparameters == null ? null : _inputparameters.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "PostalcodeHousenumber.ACT_Address_GetSingleAddress", params);
			return result == null ? null : postalcodehousenumber.proxies.Returnvalues.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<postalcodehousenumber.proxies.Returnvalues> aCT_CACPO_Get_AddressData(IContext context, postalcodehousenumber.proxies.inputparameters _inputparameters)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("inputparameters", _inputparameters == null ? null : _inputparameters.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "PostalcodeHousenumber.ACT_CACPO_Get_AddressData", params);
			java.util.List<postalcodehousenumber.proxies.Returnvalues> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<postalcodehousenumber.proxies.Returnvalues>();
				for (IMendixObject obj : objs)
					result.add(postalcodehousenumber.proxies.Returnvalues.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static postalcodehousenumber.proxies.Returnvalues aCT_Call_Address_GetSingleAddress(IContext context, postalcodehousenumber.proxies.Address _address)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Address", _address == null ? null : _address.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "PostalcodeHousenumber.ACT_Call_Address_GetSingleAddress", params);
			return result == null ? null : postalcodehousenumber.proxies.Returnvalues.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_Country_DeleteAll(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PostalcodeHousenumber.ACT_Country_DeleteAll", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<postalcodehousenumber.proxies.Returnvalues> aCT_NLBAG_Get_AddressData(IContext context, postalcodehousenumber.proxies.inputparameters _inputparameters)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("inputparameters", _inputparameters == null ? null : _inputparameters.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "PostalcodeHousenumber.ACT_NLBAG_Get_AddressData", params);
			java.util.List<postalcodehousenumber.proxies.Returnvalues> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<postalcodehousenumber.proxies.Returnvalues>();
				for (IMendixObject obj : objs)
					result.add(postalcodehousenumber.proxies.Returnvalues.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<postalcodehousenumber.proxies.Returnvalues> aCT_NLPDOK_Get_AddressData(IContext context, postalcodehousenumber.proxies.inputparameters _inputparameters)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("inputparameters", _inputparameters == null ? null : _inputparameters.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "PostalcodeHousenumber.ACT_NLPDOK_Get_AddressData", params);
			java.util.List<postalcodehousenumber.proxies.Returnvalues> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<postalcodehousenumber.proxies.Returnvalues>();
				for (IMendixObject obj : objs)
					result.add(postalcodehousenumber.proxies.Returnvalues.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static postalcodehousenumber.proxies.Returnvalues aCT_Zippomoto_GetAddressData(IContext context, postalcodehousenumber.proxies.inputparameters _inputparameters)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("inputparameters", _inputparameters == null ? null : _inputparameters.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "PostalcodeHousenumber.ACT_Zippomoto_GetAddressData", params);
			return result == null ? null : postalcodehousenumber.proxies.Returnvalues.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<postalcodehousenumber.proxies.Returnvalues> getTopxFromList(IContext context, java.util.List<postalcodehousenumber.proxies.Returnvalues> _returnvaluesList)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.ArrayList<IMendixObject> listparam_returnvaluesList = null;
			if (_returnvaluesList != null)
			{
				listparam_returnvaluesList = new java.util.ArrayList<IMendixObject>();
				for (postalcodehousenumber.proxies.Returnvalues obj : _returnvaluesList)
					listparam_returnvaluesList.add(obj.getMendixObject());
			}
			params.put("ReturnvaluesList", listparam_returnvaluesList);
			java.util.List<IMendixObject> objs = Core.execute(context, "PostalcodeHousenumber.GetTopxFromList", params);
			java.util.List<postalcodehousenumber.proxies.Returnvalues> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<postalcodehousenumber.proxies.Returnvalues>();
				for (IMendixObject obj : objs)
					result.add(postalcodehousenumber.proxies.Returnvalues.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void setup(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PostalcodeHousenumber.Setup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<postalcodehousenumber.proxies.Returnvalues> sub_Address_GetList(IContext context, postalcodehousenumber.proxies.inputparameters _inputparameters)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("inputparameters", _inputparameters == null ? null : _inputparameters.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "PostalcodeHousenumber.Sub_Address_GetList", params);
			java.util.List<postalcodehousenumber.proxies.Returnvalues> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<postalcodehousenumber.proxies.Returnvalues>();
				for (IMendixObject obj : objs)
					result.add(postalcodehousenumber.proxies.Returnvalues.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sUB_Inputvalidation(IContext context, postalcodehousenumber.proxies.inputparameters _inputparameters)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("inputparameters", _inputparameters == null ? null : _inputparameters.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "PostalcodeHousenumber.SUB_Inputvalidation", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static postalcodehousenumber.proxies.inputparameters sUB_Parse_Inputvariables(IContext context, postalcodehousenumber.proxies.inputparameters _inputparameters)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("inputparameters", _inputparameters == null ? null : _inputparameters.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "PostalcodeHousenumber.SUB_Parse_Inputvariables", params);
			return result == null ? null : postalcodehousenumber.proxies.inputparameters.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static postalcodehousenumber.proxies.Returnvalues sUB_parseGeolocationFromPOINT(IContext context, postalcodehousenumber.proxies.Returnvalues _returnvalues, java.lang.String _pOINT)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Returnvalues", _returnvalues == null ? null : _returnvalues.getMendixObject());
			params.put("POINT", _pOINT);
			IMendixObject result = (IMendixObject)Core.execute(context, "PostalcodeHousenumber.SUB_parseGeolocationFromPOINT", params);
			return result == null ? null : postalcodehousenumber.proxies.Returnvalues.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void tearDown(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PostalcodeHousenumber.TearDown", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void test_ACT_NLPDOK_Get_AddressData(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PostalcodeHousenumber.Test_ACT_NLPDOK_Get_AddressData", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void test_InputParsingAndValidation(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PostalcodeHousenumber.Test_InputParsingAndValidation", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void test_SUB_parseGeolocationFromPOINT(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PostalcodeHousenumber.Test_SUB_parseGeolocationFromPOINT", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}