// This file was generated by Mendix Modeler 7.8.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MyFirstModule module

	public static java.lang.String getWM_GUIDANCE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MyFirstModule.WM_GUIDANCE");
	}
}