// This file was generated by Mendix Modeler 7.8.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package addresslookupapi.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the AddressLookupAPI module

	/**
	* PCA predict also provides internal API key and if you are using internal API then you can set that key as default value in this constant.
	*/
	public static java.lang.String getInternalKey()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AddressLookupAPI.InternalKey");
	}

	/**
	* Set the default value of this constant with the API key provided by PCA Predict.
	*/
	public static java.lang.String getKey()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AddressLookupAPI.Key");
	}
}