// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies;

public class AddressNLPDOK
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject addressNLPDOKMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PostalcodeHousenumber.AddressNLPDOK";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AddressNLPDOK_inputparameters("PostalcodeHousenumber.AddressNLPDOK_inputparameters");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AddressNLPDOK(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PostalcodeHousenumber.AddressNLPDOK"));
	}

	protected AddressNLPDOK(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject addressNLPDOKMendixObject)
	{
		if (addressNLPDOKMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PostalcodeHousenumber.AddressNLPDOK", addressNLPDOKMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PostalcodeHousenumber.AddressNLPDOK");

		this.addressNLPDOKMendixObject = addressNLPDOKMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AddressNLPDOK.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static postalcodehousenumber.proxies.AddressNLPDOK initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return postalcodehousenumber.proxies.AddressNLPDOK.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static postalcodehousenumber.proxies.AddressNLPDOK initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new postalcodehousenumber.proxies.AddressNLPDOK(context, mendixObject);
	}

	public static postalcodehousenumber.proxies.AddressNLPDOK load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return postalcodehousenumber.proxies.AddressNLPDOK.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AddressNLPDOK_inputparameters
	 */
	public final postalcodehousenumber.proxies.inputparameters getAddressNLPDOK_inputparameters() throws com.mendix.core.CoreException
	{
		return getAddressNLPDOK_inputparameters(getContext());
	}

	/**
	 * @param context
	 * @return value of AddressNLPDOK_inputparameters
	 */
	public final postalcodehousenumber.proxies.inputparameters getAddressNLPDOK_inputparameters(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postalcodehousenumber.proxies.inputparameters result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AddressNLPDOK_inputparameters.toString());
		if (identifier != null)
			result = postalcodehousenumber.proxies.inputparameters.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AddressNLPDOK_inputparameters
	 * @param addressnlpdok_inputparameters
	 */
	public final void setAddressNLPDOK_inputparameters(postalcodehousenumber.proxies.inputparameters addressnlpdok_inputparameters)
	{
		setAddressNLPDOK_inputparameters(getContext(), addressnlpdok_inputparameters);
	}

	/**
	 * Set value of AddressNLPDOK_inputparameters
	 * @param context
	 * @param addressnlpdok_inputparameters
	 */
	public final void setAddressNLPDOK_inputparameters(com.mendix.systemwideinterfaces.core.IContext context, postalcodehousenumber.proxies.inputparameters addressnlpdok_inputparameters)
	{
		if (addressnlpdok_inputparameters == null)
			getMendixObject().setValue(context, MemberNames.AddressNLPDOK_inputparameters.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AddressNLPDOK_inputparameters.toString(), addressnlpdok_inputparameters.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return addressNLPDOKMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final postalcodehousenumber.proxies.AddressNLPDOK that = (postalcodehousenumber.proxies.AddressNLPDOK) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PostalcodeHousenumber.AddressNLPDOK";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
