// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies;

/**
 * Parameters to use when calling the microflow, and if necessary an address-API of some kind/country.
 */
public class Address
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject addressMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PostalcodeHousenumber.Address";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Country("Country"),
		Postalcode("Postalcode"),
		Housenumber("Housenumber"),
		HousenumberExtension("HousenumberExtension"),
		Housename("Housename"),
		City("City"),
		Street("Street"),
		Longitude("Longitude"),
		Latitude("Latitude"),
		Address_country("PostalcodeHousenumber.Address_country");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Address(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PostalcodeHousenumber.Address"));
	}

	protected Address(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject addressMendixObject)
	{
		if (addressMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PostalcodeHousenumber.Address", addressMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PostalcodeHousenumber.Address");

		this.addressMendixObject = addressMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Address.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static postalcodehousenumber.proxies.Address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return postalcodehousenumber.proxies.Address.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static postalcodehousenumber.proxies.Address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new postalcodehousenumber.proxies.Address(context, mendixObject);
	}

	public static postalcodehousenumber.proxies.Address load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return postalcodehousenumber.proxies.Address.initialize(context, mendixObject);
	}

	public static java.util.List<postalcodehousenumber.proxies.Address> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<postalcodehousenumber.proxies.Address> result = new java.util.ArrayList<postalcodehousenumber.proxies.Address>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PostalcodeHousenumber.Address" + xpathConstraint))
			result.add(postalcodehousenumber.proxies.Address.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Postalcode
	 */
	public final java.lang.String getPostalcode()
	{
		return getPostalcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Postalcode
	 */
	public final java.lang.String getPostalcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Postalcode.toString());
	}

	/**
	 * Set value of Postalcode
	 * @param postalcode
	 */
	public final void setPostalcode(java.lang.String postalcode)
	{
		setPostalcode(getContext(), postalcode);
	}

	/**
	 * Set value of Postalcode
	 * @param context
	 * @param postalcode
	 */
	public final void setPostalcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postalcode)
	{
		getMendixObject().setValue(context, MemberNames.Postalcode.toString(), postalcode);
	}

	/**
	 * @return value of Housenumber
	 */
	public final java.lang.Integer getHousenumber()
	{
		return getHousenumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Housenumber
	 */
	public final java.lang.Integer getHousenumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Housenumber.toString());
	}

	/**
	 * Set value of Housenumber
	 * @param housenumber
	 */
	public final void setHousenumber(java.lang.Integer housenumber)
	{
		setHousenumber(getContext(), housenumber);
	}

	/**
	 * Set value of Housenumber
	 * @param context
	 * @param housenumber
	 */
	public final void setHousenumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer housenumber)
	{
		getMendixObject().setValue(context, MemberNames.Housenumber.toString(), housenumber);
	}

	/**
	 * @return value of HousenumberExtension
	 */
	public final java.lang.String getHousenumberExtension()
	{
		return getHousenumberExtension(getContext());
	}

	/**
	 * @param context
	 * @return value of HousenumberExtension
	 */
	public final java.lang.String getHousenumberExtension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HousenumberExtension.toString());
	}

	/**
	 * Set value of HousenumberExtension
	 * @param housenumberextension
	 */
	public final void setHousenumberExtension(java.lang.String housenumberextension)
	{
		setHousenumberExtension(getContext(), housenumberextension);
	}

	/**
	 * Set value of HousenumberExtension
	 * @param context
	 * @param housenumberextension
	 */
	public final void setHousenumberExtension(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String housenumberextension)
	{
		getMendixObject().setValue(context, MemberNames.HousenumberExtension.toString(), housenumberextension);
	}

	/**
	 * @return value of Housename
	 */
	public final java.lang.String getHousename()
	{
		return getHousename(getContext());
	}

	/**
	 * @param context
	 * @return value of Housename
	 */
	public final java.lang.String getHousename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Housename.toString());
	}

	/**
	 * Set value of Housename
	 * @param housename
	 */
	public final void setHousename(java.lang.String housename)
	{
		setHousename(getContext(), housename);
	}

	/**
	 * Set value of Housename
	 * @param context
	 * @param housename
	 */
	public final void setHousename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String housename)
	{
		getMendixObject().setValue(context, MemberNames.Housename.toString(), housename);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of Street
	 */
	public final java.lang.String getStreet()
	{
		return getStreet(getContext());
	}

	/**
	 * @param context
	 * @return value of Street
	 */
	public final java.lang.String getStreet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Street.toString());
	}

	/**
	 * Set value of Street
	 * @param street
	 */
	public final void setStreet(java.lang.String street)
	{
		setStreet(getContext(), street);
	}

	/**
	 * Set value of Street
	 * @param context
	 * @param street
	 */
	public final void setStreet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String street)
	{
		getMendixObject().setValue(context, MemberNames.Street.toString(), street);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.math.BigDecimal longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.math.BigDecimal latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Address_country
	 */
	public final postalcodehousenumber.proxies.country getAddress_country() throws com.mendix.core.CoreException
	{
		return getAddress_country(getContext());
	}

	/**
	 * @param context
	 * @return value of Address_country
	 */
	public final postalcodehousenumber.proxies.country getAddress_country(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postalcodehousenumber.proxies.country result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Address_country.toString());
		if (identifier != null)
			result = postalcodehousenumber.proxies.country.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Address_country
	 * @param address_country
	 */
	public final void setAddress_country(postalcodehousenumber.proxies.country address_country)
	{
		setAddress_country(getContext(), address_country);
	}

	/**
	 * Set value of Address_country
	 * @param context
	 * @param address_country
	 */
	public final void setAddress_country(com.mendix.systemwideinterfaces.core.IContext context, postalcodehousenumber.proxies.country address_country)
	{
		if (address_country == null)
			getMendixObject().setValue(context, MemberNames.Address_country.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Address_country.toString(), address_country.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return addressMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final postalcodehousenumber.proxies.Address that = (postalcodehousenumber.proxies.Address) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PostalcodeHousenumber.Address";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
