// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies;

public class country
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject countryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PostalcodeHousenumber.country";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Alpha2code("Alpha2code"),
		Alpha3code("Alpha3code"),
		Numericcode("Numericcode"),
		Independent("Independent"),
		country_PasswordFormat("PostalcodeHousenumber.country_PasswordFormat");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public country(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PostalcodeHousenumber.country"));
	}

	protected country(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countryMendixObject)
	{
		if (countryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PostalcodeHousenumber.country", countryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PostalcodeHousenumber.country");

		this.countryMendixObject = countryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'country.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static postalcodehousenumber.proxies.country initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return postalcodehousenumber.proxies.country.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static postalcodehousenumber.proxies.country initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new postalcodehousenumber.proxies.country(context, mendixObject);
	}

	public static postalcodehousenumber.proxies.country load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return postalcodehousenumber.proxies.country.initialize(context, mendixObject);
	}

	public static java.util.List<postalcodehousenumber.proxies.country> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<postalcodehousenumber.proxies.country> result = new java.util.ArrayList<postalcodehousenumber.proxies.country>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PostalcodeHousenumber.country" + xpathConstraint))
			result.add(postalcodehousenumber.proxies.country.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Alpha2code
	 */
	public final java.lang.String getAlpha2code()
	{
		return getAlpha2code(getContext());
	}

	/**
	 * @param context
	 * @return value of Alpha2code
	 */
	public final java.lang.String getAlpha2code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Alpha2code.toString());
	}

	/**
	 * Set value of Alpha2code
	 * @param alpha2code
	 */
	public final void setAlpha2code(java.lang.String alpha2code)
	{
		setAlpha2code(getContext(), alpha2code);
	}

	/**
	 * Set value of Alpha2code
	 * @param context
	 * @param alpha2code
	 */
	public final void setAlpha2code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alpha2code)
	{
		getMendixObject().setValue(context, MemberNames.Alpha2code.toString(), alpha2code);
	}

	/**
	 * @return value of Alpha3code
	 */
	public final java.lang.String getAlpha3code()
	{
		return getAlpha3code(getContext());
	}

	/**
	 * @param context
	 * @return value of Alpha3code
	 */
	public final java.lang.String getAlpha3code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Alpha3code.toString());
	}

	/**
	 * Set value of Alpha3code
	 * @param alpha3code
	 */
	public final void setAlpha3code(java.lang.String alpha3code)
	{
		setAlpha3code(getContext(), alpha3code);
	}

	/**
	 * Set value of Alpha3code
	 * @param context
	 * @param alpha3code
	 */
	public final void setAlpha3code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alpha3code)
	{
		getMendixObject().setValue(context, MemberNames.Alpha3code.toString(), alpha3code);
	}

	/**
	 * @return value of Numericcode
	 */
	public final java.lang.Integer getNumericcode()
	{
		return getNumericcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Numericcode
	 */
	public final java.lang.Integer getNumericcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Numericcode.toString());
	}

	/**
	 * Set value of Numericcode
	 * @param numericcode
	 */
	public final void setNumericcode(java.lang.Integer numericcode)
	{
		setNumericcode(getContext(), numericcode);
	}

	/**
	 * Set value of Numericcode
	 * @param context
	 * @param numericcode
	 */
	public final void setNumericcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numericcode)
	{
		getMendixObject().setValue(context, MemberNames.Numericcode.toString(), numericcode);
	}

	/**
	 * @return value of Independent
	 */
	public final java.lang.Boolean getIndependent()
	{
		return getIndependent(getContext());
	}

	/**
	 * @param context
	 * @return value of Independent
	 */
	public final java.lang.Boolean getIndependent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Independent.toString());
	}

	/**
	 * Set value of Independent
	 * @param independent
	 */
	public final void setIndependent(java.lang.Boolean independent)
	{
		setIndependent(getContext(), independent);
	}

	/**
	 * Set value of Independent
	 * @param context
	 * @param independent
	 */
	public final void setIndependent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean independent)
	{
		getMendixObject().setValue(context, MemberNames.Independent.toString(), independent);
	}

	/**
	 * @return value of country_PasswordFormat
	 */
	public final postalcodehousenumber.proxies.PasswordFormat getcountry_PasswordFormat() throws com.mendix.core.CoreException
	{
		return getcountry_PasswordFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of country_PasswordFormat
	 */
	public final postalcodehousenumber.proxies.PasswordFormat getcountry_PasswordFormat(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postalcodehousenumber.proxies.PasswordFormat result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.country_PasswordFormat.toString());
		if (identifier != null)
			result = postalcodehousenumber.proxies.PasswordFormat.load(context, identifier);
		return result;
	}

	/**
	 * Set value of country_PasswordFormat
	 * @param country_passwordformat
	 */
	public final void setcountry_PasswordFormat(postalcodehousenumber.proxies.PasswordFormat country_passwordformat)
	{
		setcountry_PasswordFormat(getContext(), country_passwordformat);
	}

	/**
	 * Set value of country_PasswordFormat
	 * @param context
	 * @param country_passwordformat
	 */
	public final void setcountry_PasswordFormat(com.mendix.systemwideinterfaces.core.IContext context, postalcodehousenumber.proxies.PasswordFormat country_passwordformat)
	{
		if (country_passwordformat == null)
			getMendixObject().setValue(context, MemberNames.country_PasswordFormat.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.country_PasswordFormat.toString(), country_passwordformat.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return countryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final postalcodehousenumber.proxies.country that = (postalcodehousenumber.proxies.country) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PostalcodeHousenumber.country";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
