// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies;

public enum Enumeration_CountryAlpha2Codes
{
	NL(new java.lang.String[][] { new java.lang.String[] { "en_US", "NL" }, new java.lang.String[] { "nl_NL", "NL" } }),
	UK(new java.lang.String[][] { new java.lang.String[] { "en_US", "UK" }, new java.lang.String[] { "nl_NL", "UK" } }),
	DE(new java.lang.String[][] { new java.lang.String[] { "en_US", "DE" }, new java.lang.String[] { "nl_NL", "DE" } }),
	BE(new java.lang.String[][] { new java.lang.String[] { "en_US", "BE" }, new java.lang.String[] { "nl_NL", "BE" } }),
	US(new java.lang.String[][] { new java.lang.String[] { "en_US", "US" }, new java.lang.String[] { "nl_NL", "US" } }),
	FR(new java.lang.String[][] { new java.lang.String[] { "en_US", "FR" }, new java.lang.String[] { "nl_NL", "FR" } }),
	SP(new java.lang.String[][] { new java.lang.String[] { "en_US", "SP" }, new java.lang.String[] { "nl_NL", "SP" } }),
	IR(new java.lang.String[][] { new java.lang.String[] { "en_US", "IR" }, new java.lang.String[] { "nl_NL", "IR" } }),
	PO(new java.lang.String[][] { new java.lang.String[] { "en_US", "PO" }, new java.lang.String[] { "nl_NL", "PO" } }),
	IT(new java.lang.String[][] { new java.lang.String[] { "en_US", "IT" }, new java.lang.String[] { "nl_NL", "IT" } }),
	NO(new java.lang.String[][] { new java.lang.String[] { "en_US", "NO" }, new java.lang.String[] { "nl_NL", "NO" } }),
	SW(new java.lang.String[][] { new java.lang.String[] { "en_US", "SW" }, new java.lang.String[] { "nl_NL", "SW" } }),
	FI(new java.lang.String[][] { new java.lang.String[] { "en_US", "FI" }, new java.lang.String[] { "nl_NL", "FI" } }),
	DK(new java.lang.String[][] { new java.lang.String[] { "en_US", "DK" }, new java.lang.String[] { "nl_NL", "DK" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enumeration_CountryAlpha2Codes(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
