// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies;

public class housenumber
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject housenumberMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PostalcodeHousenumber.housenumber";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		Latitude("Latitude"),
		Longitude("Longitude"),
		Housenr_Zipcode("PostalcodeHousenumber.Housenr_Zipcode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public housenumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PostalcodeHousenumber.housenumber"));
	}

	protected housenumber(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject housenumberMendixObject)
	{
		if (housenumberMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PostalcodeHousenumber.housenumber", housenumberMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PostalcodeHousenumber.housenumber");

		this.housenumberMendixObject = housenumberMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'housenumber.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static postalcodehousenumber.proxies.housenumber initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return postalcodehousenumber.proxies.housenumber.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static postalcodehousenumber.proxies.housenumber initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new postalcodehousenumber.proxies.housenumber(context, mendixObject);
	}

	public static postalcodehousenumber.proxies.housenumber load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return postalcodehousenumber.proxies.housenumber.initialize(context, mendixObject);
	}

	public static java.util.List<postalcodehousenumber.proxies.housenumber> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<postalcodehousenumber.proxies.housenumber> result = new java.util.ArrayList<postalcodehousenumber.proxies.housenumber>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PostalcodeHousenumber.housenumber" + xpathConstraint))
			result.add(postalcodehousenumber.proxies.housenumber.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Number
	 */
	public final java.math.BigDecimal getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.math.BigDecimal getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.math.BigDecimal number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.lang.String getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.lang.String getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.lang.String latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.lang.String getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.lang.String getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.lang.String longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of Housenr_Zipcode
	 */
	public final postalcodehousenumber.proxies.zipcode getHousenr_Zipcode() throws com.mendix.core.CoreException
	{
		return getHousenr_Zipcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Housenr_Zipcode
	 */
	public final postalcodehousenumber.proxies.zipcode getHousenr_Zipcode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postalcodehousenumber.proxies.zipcode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Housenr_Zipcode.toString());
		if (identifier != null)
			result = postalcodehousenumber.proxies.zipcode.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Housenr_Zipcode
	 * @param housenr_zipcode
	 */
	public final void setHousenr_Zipcode(postalcodehousenumber.proxies.zipcode housenr_zipcode)
	{
		setHousenr_Zipcode(getContext(), housenr_zipcode);
	}

	/**
	 * Set value of Housenr_Zipcode
	 * @param context
	 * @param housenr_zipcode
	 */
	public final void setHousenr_Zipcode(com.mendix.systemwideinterfaces.core.IContext context, postalcodehousenumber.proxies.zipcode housenr_zipcode)
	{
		if (housenr_zipcode == null)
			getMendixObject().setValue(context, MemberNames.Housenr_Zipcode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Housenr_Zipcode.toString(), housenr_zipcode.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return housenumberMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final postalcodehousenumber.proxies.housenumber that = (postalcodehousenumber.proxies.housenumber) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PostalcodeHousenumber.housenumber";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
