// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies;

public class JsonObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PostalcodeHousenumber.JsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		Woonplaatsnaam("Woonplaatsnaam"),
		Centroide_ll("Centroide_ll"),
		Straatnaam("Straatnaam"),
		Weergavenaam("Weergavenaam"),
		Longitude("Longitude"),
		Latitude("Latitude"),
		JsonObject_AddressNLPDOK("PostalcodeHousenumber.JsonObject_AddressNLPDOK"),
		JsonObject_Places("PostalcodeHousenumber.JsonObject_Places");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PostalcodeHousenumber.JsonObject"));
	}

	protected JsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject)
	{
		if (jsonObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PostalcodeHousenumber.JsonObject", jsonObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PostalcodeHousenumber.JsonObject");

		this.jsonObjectMendixObject = jsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JsonObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static postalcodehousenumber.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return postalcodehousenumber.proxies.JsonObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static postalcodehousenumber.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new postalcodehousenumber.proxies.JsonObject(context, mendixObject);
	}

	public static postalcodehousenumber.proxies.JsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return postalcodehousenumber.proxies.JsonObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Woonplaatsnaam
	 */
	public final java.lang.String getWoonplaatsnaam()
	{
		return getWoonplaatsnaam(getContext());
	}

	/**
	 * @param context
	 * @return value of Woonplaatsnaam
	 */
	public final java.lang.String getWoonplaatsnaam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Woonplaatsnaam.toString());
	}

	/**
	 * Set value of Woonplaatsnaam
	 * @param woonplaatsnaam
	 */
	public final void setWoonplaatsnaam(java.lang.String woonplaatsnaam)
	{
		setWoonplaatsnaam(getContext(), woonplaatsnaam);
	}

	/**
	 * Set value of Woonplaatsnaam
	 * @param context
	 * @param woonplaatsnaam
	 */
	public final void setWoonplaatsnaam(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String woonplaatsnaam)
	{
		getMendixObject().setValue(context, MemberNames.Woonplaatsnaam.toString(), woonplaatsnaam);
	}

	/**
	 * @return value of Centroide_ll
	 */
	public final java.lang.String getCentroide_ll()
	{
		return getCentroide_ll(getContext());
	}

	/**
	 * @param context
	 * @return value of Centroide_ll
	 */
	public final java.lang.String getCentroide_ll(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Centroide_ll.toString());
	}

	/**
	 * Set value of Centroide_ll
	 * @param centroide_ll
	 */
	public final void setCentroide_ll(java.lang.String centroide_ll)
	{
		setCentroide_ll(getContext(), centroide_ll);
	}

	/**
	 * Set value of Centroide_ll
	 * @param context
	 * @param centroide_ll
	 */
	public final void setCentroide_ll(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String centroide_ll)
	{
		getMendixObject().setValue(context, MemberNames.Centroide_ll.toString(), centroide_ll);
	}

	/**
	 * @return value of Straatnaam
	 */
	public final java.lang.String getStraatnaam()
	{
		return getStraatnaam(getContext());
	}

	/**
	 * @param context
	 * @return value of Straatnaam
	 */
	public final java.lang.String getStraatnaam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Straatnaam.toString());
	}

	/**
	 * Set value of Straatnaam
	 * @param straatnaam
	 */
	public final void setStraatnaam(java.lang.String straatnaam)
	{
		setStraatnaam(getContext(), straatnaam);
	}

	/**
	 * Set value of Straatnaam
	 * @param context
	 * @param straatnaam
	 */
	public final void setStraatnaam(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String straatnaam)
	{
		getMendixObject().setValue(context, MemberNames.Straatnaam.toString(), straatnaam);
	}

	/**
	 * @return value of Weergavenaam
	 */
	public final java.lang.String getWeergavenaam()
	{
		return getWeergavenaam(getContext());
	}

	/**
	 * @param context
	 * @return value of Weergavenaam
	 */
	public final java.lang.String getWeergavenaam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Weergavenaam.toString());
	}

	/**
	 * Set value of Weergavenaam
	 * @param weergavenaam
	 */
	public final void setWeergavenaam(java.lang.String weergavenaam)
	{
		setWeergavenaam(getContext(), weergavenaam);
	}

	/**
	 * Set value of Weergavenaam
	 * @param context
	 * @param weergavenaam
	 */
	public final void setWeergavenaam(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String weergavenaam)
	{
		getMendixObject().setValue(context, MemberNames.Weergavenaam.toString(), weergavenaam);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.lang.String getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.lang.String getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.lang.String longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.lang.String getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.lang.String getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.lang.String latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of JsonObject_AddressNLPDOK
	 */
	public final postalcodehousenumber.proxies.AddressNLPDOK getJsonObject_AddressNLPDOK() throws com.mendix.core.CoreException
	{
		return getJsonObject_AddressNLPDOK(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_AddressNLPDOK
	 */
	public final postalcodehousenumber.proxies.AddressNLPDOK getJsonObject_AddressNLPDOK(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postalcodehousenumber.proxies.AddressNLPDOK result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_AddressNLPDOK.toString());
		if (identifier != null)
			result = postalcodehousenumber.proxies.AddressNLPDOK.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JsonObject_AddressNLPDOK
	 * @param jsonobject_addressnlpdok
	 */
	public final void setJsonObject_AddressNLPDOK(postalcodehousenumber.proxies.AddressNLPDOK jsonobject_addressnlpdok)
	{
		setJsonObject_AddressNLPDOK(getContext(), jsonobject_addressnlpdok);
	}

	/**
	 * Set value of JsonObject_AddressNLPDOK
	 * @param context
	 * @param jsonobject_addressnlpdok
	 */
	public final void setJsonObject_AddressNLPDOK(com.mendix.systemwideinterfaces.core.IContext context, postalcodehousenumber.proxies.AddressNLPDOK jsonobject_addressnlpdok)
	{
		if (jsonobject_addressnlpdok == null)
			getMendixObject().setValue(context, MemberNames.JsonObject_AddressNLPDOK.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JsonObject_AddressNLPDOK.toString(), jsonobject_addressnlpdok.getMendixObject().getId());
	}

	/**
	 * @return value of JsonObject_Places
	 */
	public final postalcodehousenumber.proxies.Places getJsonObject_Places() throws com.mendix.core.CoreException
	{
		return getJsonObject_Places(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Places
	 */
	public final postalcodehousenumber.proxies.Places getJsonObject_Places(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postalcodehousenumber.proxies.Places result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Places.toString());
		if (identifier != null)
			result = postalcodehousenumber.proxies.Places.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JsonObject_Places
	 * @param jsonobject_places
	 */
	public final void setJsonObject_Places(postalcodehousenumber.proxies.Places jsonobject_places)
	{
		setJsonObject_Places(getContext(), jsonobject_places);
	}

	/**
	 * Set value of JsonObject_Places
	 * @param context
	 * @param jsonobject_places
	 */
	public final void setJsonObject_Places(com.mendix.systemwideinterfaces.core.IContext context, postalcodehousenumber.proxies.Places jsonobject_places)
	{
		if (jsonobject_places == null)
			getMendixObject().setValue(context, MemberNames.JsonObject_Places.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JsonObject_Places.toString(), jsonobject_places.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jsonObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final postalcodehousenumber.proxies.JsonObject that = (postalcodehousenumber.proxies.JsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PostalcodeHousenumber.JsonObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
