// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies;

public enum NL_Suppliers
{
	BAG(new java.lang.String[][] { new java.lang.String[] { "en_US", "BAG - Basisadministratie Adressen en Gebouwen" }, new java.lang.String[] { "nl_NL", "BAG - Basisadministratie Adressen en Gebouwen" } }),
	PDOK(new java.lang.String[][] { new java.lang.String[] { "en_US", "PDOK - Publieke Diensten Op de Kaart" }, new java.lang.String[] { "nl_NL", "PDOK - Publieke Diensten Op de Kaart" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private NL_Suppliers(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
