// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies;

public class PasswordFormat
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject passwordFormatMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PostalcodeHousenumber.PasswordFormat";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Country("Country"),
		Regex("Regex"),
		country_PasswordFormat("PostalcodeHousenumber.country_PasswordFormat");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PasswordFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PostalcodeHousenumber.PasswordFormat"));
	}

	protected PasswordFormat(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject passwordFormatMendixObject)
	{
		if (passwordFormatMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PostalcodeHousenumber.PasswordFormat", passwordFormatMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PostalcodeHousenumber.PasswordFormat");

		this.passwordFormatMendixObject = passwordFormatMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PasswordFormat.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static postalcodehousenumber.proxies.PasswordFormat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return postalcodehousenumber.proxies.PasswordFormat.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static postalcodehousenumber.proxies.PasswordFormat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new postalcodehousenumber.proxies.PasswordFormat(context, mendixObject);
	}

	public static postalcodehousenumber.proxies.PasswordFormat load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return postalcodehousenumber.proxies.PasswordFormat.initialize(context, mendixObject);
	}

	public static java.util.List<postalcodehousenumber.proxies.PasswordFormat> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<postalcodehousenumber.proxies.PasswordFormat> result = new java.util.ArrayList<postalcodehousenumber.proxies.PasswordFormat>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PostalcodeHousenumber.PasswordFormat" + xpathConstraint))
			result.add(postalcodehousenumber.proxies.PasswordFormat.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Regex
	 */
	public final java.lang.String getRegex()
	{
		return getRegex(getContext());
	}

	/**
	 * @param context
	 * @return value of Regex
	 */
	public final java.lang.String getRegex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Regex.toString());
	}

	/**
	 * Set value of Regex
	 * @param regex
	 */
	public final void setRegex(java.lang.String regex)
	{
		setRegex(getContext(), regex);
	}

	/**
	 * Set value of Regex
	 * @param context
	 * @param regex
	 */
	public final void setRegex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String regex)
	{
		getMendixObject().setValue(context, MemberNames.Regex.toString(), regex);
	}

	/**
	 * @return value of country_PasswordFormat
	 */
	public final postalcodehousenumber.proxies.country getcountry_PasswordFormat() throws com.mendix.core.CoreException
	{
		return getcountry_PasswordFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of country_PasswordFormat
	 */
	public final postalcodehousenumber.proxies.country getcountry_PasswordFormat(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postalcodehousenumber.proxies.country result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.country_PasswordFormat.toString());
		if (identifier != null)
			result = postalcodehousenumber.proxies.country.load(context, identifier);
		return result;
	}

	/**
	 * Set value of country_PasswordFormat
	 * @param country_passwordformat
	 */
	public final void setcountry_PasswordFormat(postalcodehousenumber.proxies.country country_passwordformat)
	{
		setcountry_PasswordFormat(getContext(), country_passwordformat);
	}

	/**
	 * Set value of country_PasswordFormat
	 * @param context
	 * @param country_passwordformat
	 */
	public final void setcountry_PasswordFormat(com.mendix.systemwideinterfaces.core.IContext context, postalcodehousenumber.proxies.country country_passwordformat)
	{
		if (country_passwordformat == null)
			getMendixObject().setValue(context, MemberNames.country_PasswordFormat.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.country_PasswordFormat.toString(), country_passwordformat.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return passwordFormatMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final postalcodehousenumber.proxies.PasswordFormat that = (postalcodehousenumber.proxies.PasswordFormat) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PostalcodeHousenumber.PasswordFormat";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
