// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package postalcodehousenumber.proxies;

public class zipcode
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject zipcodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PostalcodeHousenumber.zipcode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Zipcode("Zipcode"),
		Street("Street"),
		Latitude("Latitude"),
		Longitude("Longitude"),
		Zipcode_Townvillage("PostalcodeHousenumber.Zipcode_Townvillage");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public zipcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PostalcodeHousenumber.zipcode"));
	}

	protected zipcode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject zipcodeMendixObject)
	{
		if (zipcodeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PostalcodeHousenumber.zipcode", zipcodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PostalcodeHousenumber.zipcode");

		this.zipcodeMendixObject = zipcodeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'zipcode.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static postalcodehousenumber.proxies.zipcode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return postalcodehousenumber.proxies.zipcode.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static postalcodehousenumber.proxies.zipcode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new postalcodehousenumber.proxies.zipcode(context, mendixObject);
	}

	public static postalcodehousenumber.proxies.zipcode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return postalcodehousenumber.proxies.zipcode.initialize(context, mendixObject);
	}

	public static java.util.List<postalcodehousenumber.proxies.zipcode> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<postalcodehousenumber.proxies.zipcode> result = new java.util.ArrayList<postalcodehousenumber.proxies.zipcode>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PostalcodeHousenumber.zipcode" + xpathConstraint))
			result.add(postalcodehousenumber.proxies.zipcode.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Zipcode
	 */
	public final java.lang.String getZipcode()
	{
		return getZipcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Zipcode
	 */
	public final java.lang.String getZipcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Zipcode.toString());
	}

	/**
	 * Set value of Zipcode
	 * @param zipcode
	 */
	public final void setZipcode(java.lang.String zipcode)
	{
		setZipcode(getContext(), zipcode);
	}

	/**
	 * Set value of Zipcode
	 * @param context
	 * @param zipcode
	 */
	public final void setZipcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zipcode)
	{
		getMendixObject().setValue(context, MemberNames.Zipcode.toString(), zipcode);
	}

	/**
	 * @return value of Street
	 */
	public final java.lang.String getStreet()
	{
		return getStreet(getContext());
	}

	/**
	 * @param context
	 * @return value of Street
	 */
	public final java.lang.String getStreet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Street.toString());
	}

	/**
	 * Set value of Street
	 * @param street
	 */
	public final void setStreet(java.lang.String street)
	{
		setStreet(getContext(), street);
	}

	/**
	 * Set value of Street
	 * @param context
	 * @param street
	 */
	public final void setStreet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String street)
	{
		getMendixObject().setValue(context, MemberNames.Street.toString(), street);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.lang.String getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.lang.String getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.lang.String latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.lang.String getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.lang.String getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.lang.String longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of Zipcode_Townvillage
	 */
	public final postalcodehousenumber.proxies.townvillage getZipcode_Townvillage() throws com.mendix.core.CoreException
	{
		return getZipcode_Townvillage(getContext());
	}

	/**
	 * @param context
	 * @return value of Zipcode_Townvillage
	 */
	public final postalcodehousenumber.proxies.townvillage getZipcode_Townvillage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		postalcodehousenumber.proxies.townvillage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Zipcode_Townvillage.toString());
		if (identifier != null)
			result = postalcodehousenumber.proxies.townvillage.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Zipcode_Townvillage
	 * @param zipcode_townvillage
	 */
	public final void setZipcode_Townvillage(postalcodehousenumber.proxies.townvillage zipcode_townvillage)
	{
		setZipcode_Townvillage(getContext(), zipcode_townvillage);
	}

	/**
	 * Set value of Zipcode_Townvillage
	 * @param context
	 * @param zipcode_townvillage
	 */
	public final void setZipcode_Townvillage(com.mendix.systemwideinterfaces.core.IContext context, postalcodehousenumber.proxies.townvillage zipcode_townvillage)
	{
		if (zipcode_townvillage == null)
			getMendixObject().setValue(context, MemberNames.Zipcode_Townvillage.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Zipcode_Townvillage.toString(), zipcode_townvillage.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return zipcodeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final postalcodehousenumber.proxies.zipcode that = (postalcodehousenumber.proxies.zipcode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PostalcodeHousenumber.zipcode";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
