// This file was generated by Mendix Modeler 7.8.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package addresslookupapi.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the AddressLookupAPI module
	public static addresslookupapi.proxies.PCAPredictRequest dSS_CreateInternalPCARequest(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "AddressLookupAPI.DSS_CreateInternalPCARequest", params);
			return result == null ? null : addresslookupapi.proxies.PCAPredictRequest.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static addresslookupapi.proxies.PCAPredictRequest dSS_CreatePCARequest(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "AddressLookupAPI.DSS_CreatePCARequest", params);
			return result == null ? null : addresslookupapi.proxies.PCAPredictRequest.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String iVK_CreateAPI_Key(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.String)Core.execute(context, "AddressLookupAPI.IVK_CreateAPI_Key", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ValidateAndGetAddress_AL(IContext context, addresslookupapi.proxies.PCAPredictRequest _pCAPredictRequest)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("PCAPredictRequest", _pCAPredictRequest == null ? null : _pCAPredictRequest.getMendixObject());
			Core.execute(context, "AddressLookupAPI.IVK_ValidateAndGetAddress_AL", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oC_RetriveAddressAPI(IContext context, addresslookupapi.proxies.PCAPredictResults _pCAPredictResult, addresslookupapi.proxies.PCAPredictRequest _pCAPredictRequest)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("PCAPredictResult", _pCAPredictResult == null ? null : _pCAPredictResult.getMendixObject());
			params.put("PCAPredictRequest", _pCAPredictRequest == null ? null : _pCAPredictRequest.getMendixObject());
			Core.execute(context, "AddressLookupAPI.OC_RetriveAddressAPI", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_CallFindAddressAPI(IContext context, addresslookupapi.proxies.PCAPredictRequest _pCAPredictRequest)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("PCAPredictRequest", _pCAPredictRequest == null ? null : _pCAPredictRequest.getMendixObject());
			Core.execute(context, "AddressLookupAPI.SUB_CallFindAddressAPI", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String sUB_RemoveEmptyString(IContext context, java.lang.String _postcodeString)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("PostcodeString", _postcodeString);
			return (java.lang.String)Core.execute(context, "AddressLookupAPI.SUB_RemoveEmptyString", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}